language: python

before_install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b
    - . /home/travis/miniconda3/etc/profile.d/conda.sh
    - conda update --yes conda
    - conda config --add channels r
    - conda create --yes -n test
    - conda activate test
    - conda install --yes python=3.8
    - conda install -y pycodestyle
    - conda install -y numpy
    - conda install -y matplotlib

script:
    - python src/test_FE_subroutines.py
    - bash src/test_heat2d.sh
    - pycodestyle src/test_FE_subroutines.py
    - pycodestyle src/heat2d.py
    - pycodestyle src/FE_subroutines.py
